name: sunflare
description: Projeto de estudo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  dio: ^4.0.6
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  firebase_core: ^0.4.2+2
  firebase_analytics: ^5.0.15
  firebase_crashlytics: ^0.1.4+1
  firebase_performance: ^0.3.2
  firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3


flutter:
  uses-material-design: true
  assets:
    - assets/images/