# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Firebase"
  lane :beta do
    firebase_app_distribution(
        app: '1:906514472824:android:2176d2736e903c0710f28d',
        firebase_cli_token: '1//0hvqLTrsinrCECgYIARAAGBESNwF-L9Ir-v3nzqs3pJiDnMSewRoh2VaWErpA4xp_p0VACtraWw0Wz1LPb8ALt7ni1zXDguqy8OQ',
        apk_path: '../build/app/outputs/flutter-apk/app-release.apk',
        release_notes: 'Meu release notes',
        testers: 'rodolpho@live.de',
        debug: true
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
